#!/usr/bin/env python3
from sys import argv

from database import Database

if len(argv) < 2 or argv[1] == '--help':
    print('TODO: some usage info')
    exit(0)
    
db = Database()
db.run(argv[1], argv[2:])